---
name: SteVe
version: dev
slug: steve
description: OCPP server for EV charging stations
url: https://github.com/erik73/addon-steve
arch:
  - aarch64
  - amd64
stage: experimental
ingress: true
ingress_stream: true
init: false
panel_icon: mdi:CarElectric
map:
  - ssl
services:
  - mysql:need
ports:
  80/tcp: null
  8180/tcp: 8180
  12801/tcp:
ports_description:
  80/tcp: Web interface
  8180/tcp: SteVe TCP port
  12801/tcp: SteVe SOAP return port
hassio_api: true
options:
  timezone: CET
  admin_user: admin
  admin_password:
schema:
  timezone: str
  admin_user: str
  admin_password: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
